---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: temporal
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/temporalio/helm-charts.git
    targetRevision: v1.22.4
    path: charts/temporal
    helm:
      values: |
        server:
          replicaCount: 1
        cassandra:
          config:
            cluster_size: 1
        elasticsearch
          replicas: 1
        prometheus:
          enabled: false
        grafana:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: temporal
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
