---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nessie
  namespace: dremio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nessie
  template:
    metadata:
      labels:
        app: nessie
    spec:
      containers:
      - name: nessie
        image: projectnessie/nessie:latest
        ports:
        - containerPort: 19120
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dremio
  namespace: dremio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dremio
  template:
    metadata:
      labels:
        app: dremio
    spec:
      containers:
      - name: dremio
        image: dremio/dremio-oss:latest
        ports:
        - containerPort: 9047
        - containerPort: 31010
        - containerPort: 32010
        env:
        - name: DREMIO_JAVA_SERVER_EXTRA_OPTS
          value: "-Dpaths.dist=file:///opt/dremio/data/dist"
