---
apiVersion: v1
kind: Service
metadata:
  name: nessie
  namespace: dremio
spec:
  selector:
    app: nessie
  ports:
  - protocol: TCP
    port: 19120 # Service port
    targetPort: 19120 # Container port
  type: ClusterIP # Use ClusterIP for internal communication
---
apiVersion: v1
kind: Service
metadata:
  name: dremio
  namespace: dremio
spec:
  selector:
    app: dremio
  ports:
    - name: ui
      protocol: TCP
      port: 9047 # Dremio UI
      targetPort: 9047
    - name: client
      protocol: TCP
      port: 31010 # Dremio client
      targetPort: 31010
    - name: coordinator
      protocol: TCP
      port: 32010 # Dremio coordinator
      targetPort: 32010
  type: ClusterIP # Use ClusterIP for internal communication
