---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: "https://github.com/rodrigc/eks-cluster1-yaml.git"
    targetRevision: main
    path: infrastructure/argo-cd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
